# FROM https://jekyllrb.com/docs/continuous-integration/travis-ci/
# with some modifications

dist: bionic

language: ruby

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# https://docs.travis-ci.com/user/languages/ruby/#bundler-20
before_install:
# FIXME blocked by default Ruby version
  - yes | gem update --system --force
  - gem install bundler

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
