# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS 498 VR
description: >- # this means to ignore newlines until "baseurl:"
  © University of Illinois, 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cs498vr.cs.illinois.edu" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  illinois-cs498vr
issues: https://github.com/illinois-cs498vr/illinois-cs498vr.github.io/issues/new

semester:
  piazza: https://piazza.com/illinois/spring2019/cs498vr
  location: 1320 Digital Computer Lab
  time: MW 4-5:15pm
  midterm1: Feb. 10 - Feb. 12
  secondChance1: Feb. 17 - Feb. 19
  midterm2: Mar. 10 - Mar. 12
  secondChance2: Mar. 25 - Mar. 26
  midterm3: Apr. 28 - Apr. 30
# Build settings
markdown: kramdown
theme: minima

collections:
  assignments:
    output: true
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - .gitignore
  - .git/

# Information about the lab
lab:
  room: 4107 Siebel
  unity-version: 2018.2.14